CREATE TABLE `maintenance_items` (
	`id` text PRIMARY KEY NOT NULL,
	`maintenance_log_id` text NOT NULL,
	`item_name` text NOT NULL,
	`item_description` text,
	`quantity` integer DEFAULT 1 NOT NULL,
	`unit_cost` real,
	`total_cost` real,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`maintenance_log_id`) REFERENCES `maintenance_logs`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `maintenance_logs` (
	`id` text PRIMARY KEY NOT NULL,
	`truck_id` text NOT NULL,
	`maintenance_staff_id` text NOT NULL,
	`inspection_date` integer NOT NULL,
	`inspection_time` text,
	`inspector_name` text NOT NULL,
	`location_of_inspection` text,
	`odometer_reading` integer NOT NULL,
	`hour_meter` integer,
	`body_and_seats` integer DEFAULT false,
	`chassis_frame` integer DEFAULT false,
	`underbody` integer DEFAULT false,
	`driver_shaft` integer DEFAULT false,
	`windows_and_mirror` integer DEFAULT false,
	`fuel` integer DEFAULT false,
	`exhaust` integer DEFAULT false,
	`friction_components` integer DEFAULT false,
	`hydraulic_and_vacuum_assist_brake` integer DEFAULT false,
	`mechanical_components` integer DEFAULT false,
	`brake_pedal` integer DEFAULT false,
	`air_brake_system` integer DEFAULT false,
	`park_brake` integer DEFAULT false,
	`brake_system` integer DEFAULT false,
	`engine_controls` integer DEFAULT false,
	`steering_column_and_box` integer DEFAULT false,
	`wheel_alignment` integer DEFAULT false,
	`steering_linkage` integer DEFAULT false,
	`suspension` integer DEFAULT false,
	`general_requirements` integer DEFAULT false,
	`fire_extinguisher` integer DEFAULT false,
	`spill_kit` integer DEFAULT false,
	`first_aid_kit` integer DEFAULT false,
	`shovel` integer DEFAULT false,
	`axe` integer DEFAULT false,
	`track_shovel` integer DEFAULT false,
	`grease_gun` integer DEFAULT false,
	`windshield_wiper_and_wash` integer DEFAULT false,
	`heating_and_defrosting_system` integer DEFAULT false,
	`starting_switch` integer DEFAULT false,
	`lamps_and_reflectors` integer DEFAULT false,
	`tires` integer DEFAULT false,
	`wheels` integer DEFAULT false,
	`diffs` integer DEFAULT false,
	`coolant` integer DEFAULT false,
	`vhf_radio` integer DEFAULT false,
	`am_fm_radio` integer DEFAULT false,
	`grease` integer DEFAULT false,
	`air_filter` integer DEFAULT false,
	`air_conditioning` integer DEFAULT false,
	`fan_belts` integer DEFAULT false,
	`planetary_oil` integer DEFAULT false,
	`hydraulic_oil` integer DEFAULT false,
	`drum_oil` integer DEFAULT false,
	`engine_oil` integer DEFAULT false,
	`transmission_oil` integer DEFAULT false,
	`winch_oil` integer DEFAULT false,
	`swing_oil` integer DEFAULT false,
	`maintenance_notes` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`truck_id`) REFERENCES `trucks`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`maintenance_staff_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE restrict
);
--> statement-breakpoint
CREATE TABLE `billing_rates` (
	`id` text PRIMARY KEY NOT NULL,
	`rate_name` text NOT NULL,
	`rate_per_hour` real NOT NULL,
	`currency` text DEFAULT 'USD' NOT NULL,
	`description` text,
	`is_active` integer DEFAULT true,
	`created_by` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `billing_rates_rate_name_unique` ON `billing_rates` (`rate_name`);--> statement-breakpoint
CREATE TABLE `timesheets` (
	`id` text PRIMARY KEY NOT NULL,
	`driver_id` text NOT NULL,
	`truck_id` text NOT NULL,
	`shift_start_date` integer NOT NULL,
	`shift_end_date` integer,
	`start_odometer_reading` integer,
	`end_odometer_reading` integer NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`approved_by` text,
	`approved_at` integer,
	`rejection_reason` text,
	`billing_rate_id` text,
	`total_billed_amount` real,
	`notes` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`driver_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`truck_id`) REFERENCES `trucks`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`billing_rate_id`) REFERENCES `billing_rates`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `trucks` (
	`id` text PRIMARY KEY NOT NULL,
	`unit_number` text NOT NULL,
	`make` text,
	`model` text,
	`serial_number` text,
	`last_odometer_reading` integer DEFAULT 0,
	`maintenance_interval_km` integer DEFAULT 10000 NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `trucks_unit_number_unique` ON `trucks` (`unit_number`);--> statement-breakpoint
CREATE UNIQUE INDEX `trucks_serial_number_unique` ON `trucks` (`serial_number`);